"""There is FUN in FUNeral

Revision ID: 1507f244543c
Revises: be3147ce4024
Create Date: 2024-12-19 06:41:15.877381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1507f244543c'
down_revision = 'be3147ce4024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
